### ISSUE TITLE
sent a payment via paypal.

### ISSUE THREAD

**Issue by ellavondegurechaff** [kingparks/cursor-vip#74]
DEVICE ID: a89911a2125c5c37207fdf99e21f3b78

**Comment by ellavondegurechaff** [comment]
@kingparks

**Comment by ellavondegurechaff** [comment]
0d 13h 9m 0spanic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x28 pc=0x608cc9]

goroutine 1 [running]:
github.com/kingparks/cursor-vip/auth.getHash({0x0?, 0xc0002a1bf0?})
        /Users/au/dev/my/cursor-vip/auth/client_cursor.go:125 +0x29
github.com/kingparks/cursor-vip/auth.setClient({0x6de4ed?, 0x9e85b?})
        /Users/au/dev/my/cursor-vip/auth/auth.go:175 +0x1d1
github.com/kingparks/cursor-vip/auth.Run({0x6de4ed, 0xa}, 0x1)
        /Users/au/dev/my/cursor-vip/auth/auth.go:121 +0x9c
main.startServer({0x6de4ed, 0xa}, 0x1)
        /Users/au/dev/my/cursor-vip/main.go:31 +0x1f1
main.main()
        /Users/au/dev/my/cursor-vip/main.go:16 +0x18

GO routine problem

**Comment by kingparks** [comment]
just update :
```sh
bash <(curl -Lk https://github.com/kingparks/cursor-vip/releases/download/latest/i.sh)
```

**Comment by kingparks** [comment]
> DEVICE ID: a89911a2125c5c37207fdf99e21f3b78

https://github.com/kingparks/cursor-vip/issues/68#issuecomment-2556453219

**Comment by ellavondegurechaff** [comment]
![image](https://github.com/user-attachments/assets/cd32bf7a-3edf-4815-9deb-afc231c5128e)
i updated it. also i already paid for the 30$ in your paypal.
![image](https://github.com/user-attachments/assets/f047be99-666b-4525-8458-a008e4757aea)

**Comment by kingparks** [comment]
Patrick Martiel Franco is you?

**Comment by ellavondegurechaff** [comment]
yes

**Comment by kingparks** [comment]
Done
exp at 2025-12-22 13:07:17
thx for your support

**Comment by ellavondegurechaff** [comment]
thank you! im still getting this error:
Authorization successful! Please do not close this window during use
365d 12h 59m 13spanic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x28 pc=0x10f8cc9]

goroutine 1 [running]:
github.com/kingparks/cursor-vip/auth.getHash({0x0?, 0xc000223bf0?})
        /Users/au/dev/my/cursor-vip/auth/client_cursor.go:125 +0x29
github.com/kingparks/cursor-vip/auth.setClient({0x11ce4ed?, 0xb8e85b?})
        /Users/au/dev/my/cursor-vip/auth/auth.go:175 +0x1d1
github.com/kingparks/cursor-vip/auth.Run({0x11ce4ed, 0xa}, 0x1)
        /Users/au/dev/my/cursor-vip/auth/auth.go:121 +0x9c
main.startServer({0x11ce4ed, 0xa}, 0x1)
        /Users/au/dev/my/cursor-vip/main.go:31 +0x1f1
main.main()
        /Users/au/dev/my/cursor-vip/main.go:16 +0x18


i used the latest and updated it.

**Comment by kingparks** [comment]
> ![image](https://private-user-images.githubusercontent.com/65035681/397938570-cd32bf7a-3edf-4815-9deb-afc231c5128e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3OTczNzEsIm5iZiI6MTczNDc5NzA3MSwicGF0aCI6Ii82NTAzNTY4MS8zOTc5Mzg1NzAtY2QzMmJmN2EtM2VkZi00ODE1LTlkZWItYWZjMjMxYzUxMjhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIxVDE2MDQzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmNDBiNDg0OWQ1YzMwNTc1ODY5ZDc2YTUyNWU5YzA0Njc1MjkxOThlMGI5OWU0YTMzNmI4NDQ3OTlhZmViMzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.JR8yqieE7Og2l1z4KQoq4Gmhc2YON4woGgmZ9iAz1-M) i updated it. also i already paid for the 30$ in your paypal. ![image](https://private-user-images.githubusercontent.com/65035681/397938600-f047be99-666b-4525-8458-a008e4757aea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3OTczNzEsIm5iZiI6MTczNDc5NzA3MSwicGF0aCI6Ii82NTAzNTY4MS8zOTc5Mzg2MDAtZjA0N2JlOTktNjY2Yi00NTI1LTg0NTgtYTAwOGU0NzU3YWVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIxVDE2MDQzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlOTg1MDZiYzgwM2I3NmE4ZTE2MGQ5YjlmODE1ODNjYWU4Y2JiNWQ4MTFiZGQyY2IxYWZmMWVkNzBjYjkyNmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.a-BgwNnivq3x_mpNKRhuK40U0OLUtnkFJKUcPpKtv3Y)

get , I will fix now

**Comment by kingparks** [comment]
fixed, up to v2.3.7

bash <(curl -Lk https://github.com/kingparks/cursor-vip/releases/download/latest/i.sh)
